# Generated by Django 2.1.4 on 2018-12-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coonboardingtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboard_company', to='projectx_app.SystemCompanySetup'),
        ),
    ]
