# Generated by Django 2.1.4 on 2018-12-23 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0004_auto_20181223_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Company Vendor', 'verbose_name_plural': 'Company Vendors'},
        ),
        migrations.AlterModelOptions(
            name='vendormaster',
            options={'verbose_name': 'Vendor Master', 'verbose_name_plural': 'Vendor Masters'},
        ),
        migrations.AddField(
            model_name='vendormaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendormaster',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_master_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendormaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_user_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
