# Generated by Django 2.1.4 on 2018-12-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0005_auto_20181223_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormaster',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
    ]
