# Generated by Django 2.1.4 on 2018-12-24 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0006_auto_20181223_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_company', to='projectx_app.SystemCompanySetup'),
        ),
    ]
