# Generated by Django 2.1.4 on 2018-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0009_auto_20181224_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor',
            field=models.ManyToManyField(blank=True, null=True, to='projectx_app.VendorMaster'),
        ),
    ]
