# Generated by Django 2.1.4 on 2018-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0010_auto_20181224_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor',
            field=models.ManyToManyField(to='projectx_app.VendorMaster'),
        ),
    ]
