# Generated by Django 2.1.4 on 2018-12-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0011_auto_20181224_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectx_app.VendorMaster'),
        ),
    ]
