# Generated by Django 2.1.4 on 2018-12-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0014_auto_20181224_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contract_end_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contract End Date'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contract_start_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contract Start Date'),
        ),
    ]
