# Generated by Django 2.1.4 on 2018-12-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0016_auto_20181225_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='updated_at',
        ),
    ]
