# Generated by Django 2.1.4 on 2018-12-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0017_auto_20181225_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormaster',
            name='service_provider_type',
            field=models.CharField(blank=True, choices=[('external', 'External'), ('internal', 'Internal')], default='external', max_length=256, null=True),
        ),
    ]
