# Generated by Django 2.1.4 on 2018-12-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0018_vendormaster_service_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequest',
            name='hiring_manager',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Hiring Manager'),
        ),
        migrations.AddField(
            model_name='myrequest',
            name='job_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Job Id'),
        ),
        migrations.AddField(
            model_name='myrequest',
            name='position_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Position Id'),
        ),
        migrations.AddField(
            model_name='myrequest',
            name='recruiter',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Recruiter'),
        ),
    ]
