# Generated by Django 2.1.4 on 2018-12-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0019_auto_20181226_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksbgvdocs',
            name='bgv_task_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='my_bgv_request', to='projectx_app.CoOnboardingTaskBGV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myrequesttaskshrdocs',
            name='hrtask_task_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_hr_request', to='projectx_app.CoOnboardingTaskHrForm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myrequesttasksrefdocs',
            name='refcheck_task_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='my_reference_request', to='projectx_app.CoOnboardingTaskRefCheck'),
            preserve_default=False,
        ),
    ]
