# Generated by Django 2.1.4 on 2018-12-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0021_auto_20181227_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasks',
            name='step_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='myrequesttasks',
            name='task_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Task Name'),
        ),
        migrations.AddField(
            model_name='myrequesttasks',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_request_vendor', to='projectx_app.Vendor'),
        ),
        migrations.AlterField(
            model_name='myrequesttasks',
            name='request_due_date',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='request_due_date'),
        ),
    ]
