# Generated by Django 2.1.4 on 2018-12-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0022_auto_20181227_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasks',
            name='co_onboarding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_onboarding_type', to='projectx_app.CoOnboardingType'),
        ),
        migrations.AlterField(
            model_name='myrequesttasks',
            name='myrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_request', to='projectx_app.MyRequest'),
        ),
        migrations.AlterField(
            model_name='myrequesttasks',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_task', to='projectx_app.CoOnboardingTask'),
        ),
    ]
