# Generated by Django 2.1.4 on 2018-12-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0023_auto_20181227_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRequestTasksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(blank=True, max_length=256, null=True)),
                ('task_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Task Name')),
                ('request_due_date', models.CharField(blank=True, max_length=256, null=True, verbose_name='requestinfo_due_date')),
                ('co_onboarding_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestinfo_onboarding_type', to='projectx_app.CoOnboardingType')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectx_app.SystemCompanySetup')),
                ('myrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_requestinfo', to='projectx_app.MyRequest')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestinfo_task', to='projectx_app.CoOnboardingTask')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestinfo_vendor', to='projectx_app.Vendor')),
            ],
            options={
                'verbose_name': 'My Request Task Info',
                'verbose_name_plural': 'My Request Task Infos',
            },
        ),
    ]
