# Generated by Django 2.1.4 on 2018-12-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0027_auto_20181231_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], default='Initiated', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='result',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('All Clear', 'All Clear'), ('Completed', 'Completed'), ('Requested Docs', 'Requested Docs')], default='Pending', max_length=100, null=True),
        ),
    ]
