# Generated by Django 2.1.4 on 2019-01-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0029_remove_systemcompanysetup_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyuser',
            old_name='system_company',
            new_name='company',
        ),
    ]
