# Generated by Django 2.1.4 on 2019-01-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0031_auto_20190102_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcompanysetup',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='logo'),
        ),
    ]
