# Generated by Django 2.1.4 on 2019-01-03 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0033_auto_20190103_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoruser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vendoruser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendoruser',
            name='vendor',
        ),
        migrations.AddField(
            model_name='companyvendor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coonboardingtask',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_vendor', to='projectx_app.CompanyVendor'),
        ),
        migrations.AlterField(
            model_name='myrequesttasks',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_request_vendor', to='projectx_app.CompanyVendor'),
        ),
        migrations.AlterField(
            model_name='myrequesttasksinfo',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestinfo_vendor', to='projectx_app.CompanyVendor'),
        ),
        migrations.DeleteModel(
            name='VendorUser',
        ),
    ]
