# Generated by Django 2.1.4 on 2019-01-03 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0035_auto_20190103_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvendor',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectx_app.VendorMaster'),
        ),
    ]
