# Generated by Django 2.1.4 on 2019-01-03 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0036_auto_20190103_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvendor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
