# Generated by Django 2.1.4 on 2019-01-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0039_auto_20190103_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcheck',
            name='myrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_my_request', to='projectx_app.MyRequest'),
        ),
    ]
