# Generated by Django 2.1.4 on 2019-01-04 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0040_auto_20190103_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Email')),
                ('due_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Due Date')),
                ('attached_template', models.FileField(blank=True, null=True, upload_to='', verbose_name='Attached Template')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('myrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_my_request', to='projectx_app.MyRequest')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_owner', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_check_vendor', to='projectx_app.CompanyVendor')),
            ],
            options={
                'verbose_name': 'Travel Booking',
                'verbose_name_plural': 'Travel Bookings',
            },
        ),
    ]
