# Generated by Django 2.1.4 on 2019-01-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0041_travelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='vendor_files/', verbose_name='File Name'),
        ),
    ]
