# Generated by Django 2.1.4 on 2019-01-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0042_myrequesttasksinfo_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
