# Generated by Django 2.1.4 on 2019-01-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0043_myrequesttasksinfo_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coonboardingtaskhrform',
            options={'verbose_name': 'Company On-Boarding HR', 'verbose_name_plural': 'Company On-Boarding HRs'},
        ),
        migrations.AlterModelOptions(
            name='coonboardingtaskrefcheck',
            options={'verbose_name': 'Company On-Boarding REF', 'verbose_name_plural': 'Company On-Boarding REFs'},
        ),
        migrations.AlterField(
            model_name='systemcompanysetup',
            name='rpo_provider',
            field=models.BooleanField(default=False, verbose_name='RPO Provider'),
        ),
    ]
