# Generated by Django 2.1.4 on 2019-01-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0047_auto_20190105_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcompanysetup',
            name='rpo_provider',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=False, null=True, verbose_name='RPO Provider'),
        ),
    ]
