# Generated by Django 2.1.4 on 2019-01-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0048_auto_20190105_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcompanysetup',
            name='rpo_provider',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='RPO Provider'),
        ),
    ]
