# Generated by Django 2.1.4 on 2019-01-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0050_auto_20190106_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
