# Generated by Django 2.1.4 on 2019-01-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0051_personalinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttaskshrdocs',
            name='not_applicable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Request Not Applicable'),
        ),
        migrations.AlterField(
            model_name='myrequesttaskshrdocs',
            name='mark_complete',
            field=models.BooleanField(blank=True, null=True, verbose_name='Request Mark Complete'),
        ),
    ]
