# Generated by Django 2.1.4 on 2019-01-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0052_auto_20190109_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrequesttaskshrdocs',
            name='hrtask_task_id',
        ),
        migrations.RemoveField(
            model_name='myrequesttasksrefdocs',
            name='refcheck_task_id',
        ),
    ]
