# Generated by Django 2.1.4 on 2019-01-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0055_myrequesttasksrefdocs_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksrefdocs',
            name='row_index',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
