# Generated by Django 2.1.4 on 2019-01-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0057_myrequesttasksrefdocs_ref_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='vendor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestinfo_vendor_user', to='projectx_app.CompanyVendor'),
        ),
    ]
