# Generated by Django 2.1.4 on 2019-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0058_myrequesttasksinfo_vendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcompanysetup',
            name='logo_image',
            field=models.ImageField(blank=True, height_field='92', upload_to='', verbose_name='logo', width_field='92'),
        ),
    ]
