# Generated by Django 2.1.4 on 2019-01-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0059_auto_20190111_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcompanysetup',
            name='logo_image',
            field=models.ImageField(blank=True, height_field=92, upload_to='', verbose_name='logo', width_field=92),
        ),
    ]
