# Generated by Django 2.1.4 on 2019-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0061_auto_20190111_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcompanysetup',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='logo'),
        ),
    ]
