# Generated by Django 2.1.4 on 2019-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0062_auto_20190111_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrequesttasksinfo',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
