# Generated by Django 2.1.4 on 2019-01-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0063_auto_20190111_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrequesttasksinfo',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myrequesttasksinfo',
            name='result',
            field=models.CharField(blank=True, choices=[('All Clear', 'All Clear'), ('Request can not be processed', 'Request can not be processed'), ('Document Requested again', 'Document Requested again'), ('Failed', 'Failed')], default='Pending', max_length=100, null=True),
        ),
    ]
