# Generated by Django 2.1.4 on 2019-01-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0064_auto_20190115_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='nameChanged',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
