# Generated by Django 2.1.4 on 2019-01-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0065_auto_20190119_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRequestTaskBGV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrequest_bgv_document', to='projectx_app.DocumentTypeName')),
                ('myrequest_tasks_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrequest_bgv_task', to='projectx_app.MyRequestTasksInfo')),
            ],
            options={
                'verbose_name': 'My Request BGV',
                'verbose_name_plural': 'My Request BGVs',
            },
        ),
    ]
