# Generated by Django 2.1.4 on 2019-01-23 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0066_myrequesttaskbgv'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRequestTaskRefCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_references', models.CharField(max_length=5, verbose_name='Number of Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('myrequest_tasks_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrequest_ref_task', to='projectx_app.MyRequestTasksInfo')),
                ('reference_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrequest_sys_ref', to='projectx_app.SysRefCheck')),
            ],
            options={
                'verbose_name_plural': 'My Request REFs',
                'verbose_name': 'My Request REF',
            },
        ),
    ]
