# Generated by Django 2.1.4 on 2019-01-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0068_myrequesttaskhrform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrequesttasks',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_task', to='projectx_app.MyRequestTasksInfo'),
        ),
    ]
