# Generated by Django 2.1.4 on 2019-01-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0069_auto_20190124_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'applicant'), (2, 'companyadmin'), (3, 'vendor'), (4, 'caseworker'), (5, 'rpo'), (6, 'companyuser'), (7, 'CMO'), (8, 'Hiring Manager')], null=True),
        ),
    ]
