# Generated by Django 2.1.4 on 2019-02-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0071_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload File'),
        ),
    ]
