# Generated by Django 2.1.4 on 2019-02-04 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0072_reimbursement_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_reimbursment', to='projectx_app.Applicant'),
        ),
    ]
