# Generated by Django 2.1.4 on 2019-02-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0073_reimbursement_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='reimbursementName',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
