# Generated by Django 2.1.4 on 2019-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0074_reimbursement_reimbursementname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='reimbursementName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
