# Generated by Django 2.1.4 on 2019-02-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0075_auto_20190204_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='reimbursementName',
        ),
    ]
