# Generated by Django 2.1.4 on 2019-02-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0076_remove_reimbursement_reimbursementname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='applicant',
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='applicant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_user_reimbursment', to=settings.AUTH_USER_MODEL),
        ),
    ]
