# Generated by Django 2.1.4 on 2019-02-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0077_auto_20190204_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='applicant_user',
        ),
    ]
