# Generated by Django 2.1.4 on 2019-02-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0078_remove_reimbursement_applicant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='my-reimbursement/', verbose_name='Document File')),
            ],
            options={
                'verbose_name': 'Reimbursement Document',
                'verbose_name_plural': 'Reimbursement Documents',
            },
        ),
        migrations.RemoveField(
            model_name='reimbursement',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='reimbursementdocument',
            name='reimbursement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_file', to='projectx_app.Reimbursement'),
        ),
    ]
