# Generated by Django 2.1.4 on 2019-02-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0080_auto_20190204_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOnboardingTaskMedicalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('onboarding_medical_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_medical_task', to='projectx_app.CoOnboardingTask')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_medical_templates', to='projectx_app.Template')),
            ],
            options={
                'verbose_name': 'Company On-Boarding Medical',
                'verbose_name_plural': 'Company On-Boarding Medicals',
            },
        ),
    ]
