# Generated by Django 2.1.4 on 2019-02-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0082_myrequesttaskmedicalform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myrequesttaskmedicalform',
            options={'verbose_name': 'My Request Medical', 'verbose_name_plural': 'My Request Medicals'},
        ),
    ]
