# Generated by Django 2.1.4 on 2019-02-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0084_myrequesttasksinfo_medical_cmo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRequestTasksMedicalDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.FileField(blank=True, null=True, upload_to='', verbose_name='Document Name')),
                ('mark_complete', models.BooleanField(blank=True, null=True, verbose_name='Request Mark Complete')),
                ('not_applicable', models.BooleanField(blank=True, null=True, verbose_name='Request Not Applicable')),
                ('myrequest_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_medical_task', to='projectx_app.MyRequestTasks')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_medical_template', to='projectx_app.Template')),
            ],
            options={
                'verbose_name': 'My Request Medical Document',
                'verbose_name_plural': 'My Request Medical Documents',
            },
        ),
    ]
