# Generated by Django 2.1.4 on 2019-02-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0088_auto_20190207_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrequesttasksinfo',
            name='medical_cmo_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_medical_cmo_user', to='projectx_app.CompanyUser', verbose_name='Medical CMO User'),
        ),
    ]
