# Generated by Django 2.1.4 on 2019-02-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0090_myrequesttasksinfo_result_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequest',
            name='hiring_manager_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myrequest_hiring_manager', to='projectx_app.CompanyUser', verbose_name='Hiring Manager User'),
        ),
    ]
