# Generated by Django 2.1.4 on 2019-02-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0091_myrequest_hiring_manager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='is_vendor_action',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Vendor Actioned'),
        ),
    ]
