# Generated by Django 2.1.4 on 2019-02-11 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0092_myrequesttasksinfo_is_vendor_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPOUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'RPO User',
                'verbose_name_plural': 'RPO Users',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'applicant'), (2, 'companyadmin'), (3, 'vendor'), (4, 'caseworker'), (5, 'rpo'), (6, 'companyuser'), (7, 'CMO'), (8, 'Hiring Manager'), (9, 'rpouser')], null=True),
        ),
        migrations.AddField(
            model_name='rpouser',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpouser_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rpouser',
            name='rpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sysrpo_user', to='projectx_app.SysRpo'),
        ),
        migrations.AddField(
            model_name='rpouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rpo_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
