# Generated by Django 2.1.4 on 2019-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0094_myrequesttasksinfo_is_cmo_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='is_hiring_manager_action',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Hiring Manager Actioned'),
        ),
    ]
