# Generated by Django 2.1.4 on 2019-02-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0095_myrequesttasksinfo_is_hiring_manager_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='homeNumberCode',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='workNumberCode',
        ),
    ]
