# Generated by Django 2.1.4 on 2019-02-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0099_auto_20190214_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrequesttasksinfo',
            name='hiring_manager_status',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=100, null=True),
        ),
    ]
