# Generated by Django 2.1.4 on 2019-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0100_auto_20190214_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='cmo_manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='CMO Manager Comments'),
        ),
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='cmo_manager_status',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=100, null=True),
        ),
    ]
