# Generated by Django 2.1.4 on 2019-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0102_coonboardingtask_send_to_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrequesttasksinfo',
            name='send_to_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
