# Generated by Django 2.1.4 on 2019-02-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0104_myrequesttasks_send_to_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrequesttasksinfo',
            name='result',
            field=models.CharField(blank=True, choices=[('All Clear', 'All Clear'), ('Request can not be processed', 'Request can not be processed'), ('Document Requested again', 'Document Requested again'), ('Minor Issues', 'Minor Issues'), ('Serious medical condition', 'Serious medical condition'), ('Failed', 'Failed')], default='Pending', max_length=100, null=True),
        ),
    ]
