# Generated by Django 2.1.4 on 2019-02-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0105_auto_20190220_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='temp_postalCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
