# Generated by Django 2.1.4 on 2019-02-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0106_auto_20190220_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('Refuse to answer', 'Refuse to answer')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='maritalStatus',
            field=models.CharField(blank=True, choices=[('MARRIED', 'Married'), ('UNMARRIED', 'Unmarried'), ('Refuse to answer', 'Refuse to answer')], max_length=256, null=True),
        ),
    ]
