# Generated by Django 2.1.4 on 2019-02-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0107_auto_20190221_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyvendor',
            options={},
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='perm_postalCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='companyvendor',
            unique_together={('user', 'company', 'vendor')},
        ),
    ]
