# Generated by Django 2.1.4 on 2019-02-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0108_auto_20190221_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvendor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_master', to='projectx_app.SystemCompanySetup'),
        ),
        migrations.AlterField(
            model_name='companyvendor',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_master', to='projectx_app.VendorMaster'),
        ),
    ]
