# Generated by Django 2.1.4 on 2019-03-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx_app', '0110_user_is_password_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('otp_number', models.CharField(max_length=10, verbose_name='OTP Number')),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'USER OTPS',
                'verbose_name': 'USER OTP',
            },
        ),
    ]
